---
title: "FAQs"
output: html_document
---

## Installation  
- [First time R package installation](./installation_issues.html#first-time-r-package-installation)
- [Manual python installation](./installation_issues.html#python-manual-installation)
- [Clang error on MacOS](./installation_issues.html#errors-on-macos)
- [Error: 'make' not found](./installation_issues.html#make-not-found-error)
- [Error converted from warning](./installation_issues.html#error-converted-from-warning)
- [R 3.6.3 and Catalina issue](./installation_issues.html#errors-on-macos)

## Data availability  
- Where to find seqFISH+ and other ready-to-use datasets?  
**Checkout https://github.com/RubD/spatial-datasets to find already preprocessed datasets**  

- Where to find other spatial datasets?  
**Checkout https://www.spatialomics.org/SpatialDB/ to download expression matrix and location information**

- How to automatically download tutorial datasets? (merFISH example)

```{r eval=FALSE, }
# choose your directory
my_working_dir = getwd()

# standard download data to working directory
getSpatialDataset(dataset = 'merfish_preoptic', directory = my_working_dir)

# use wget to  download data to working directory (much faster)
getSpatialDataset(dataset = 'merfish_preoptic', directory = my_working_dir, method = 'wget')

# avoid certification issues with wget
getSpatialDataset(dataset = 'merfish_preoptic', directory = my_working_dir, method = 'wget', extra = '--no-check-certificate')

# see download.file for more options
?download.file
```
